controller:
  installPlugins:
    # need to add this configuration-as-code due to a known jenkins issue: https://github.com/jenkinsci/helm-charts/issues/595
  # - "configuration-as-code:1414.v878271fc496f"
  - "configuration-as-code:1512.vb_79d418d5fc8"
  - "hashicorp-vault-plugin:latest"
  - "workflow-aggregator:590.v6a_d052e5a_a_b_5"
  - "blueocean:1.25.8"
  - "job-dsl:1.81"

  # passing initial environments values to docker basic container
  # InitContainerEnv:

  containerEnv:
  - name: CASC_VAULT_TOKEN
    value: "root"
  - name: CASC_VAULT_URL
    value: "http://192.168.65.2:8200"
  - name: CASC_VAULT_PATHS
    value: "secret/jenkins"
  - name: CASC_VAULT_ENGINE_VERSION
    value: "2"

  JCasC:
    configScripts:
      this-is-where-i-configure-the-executors: |
        jenkins:
          numExecutors: 5
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin by AlanMas, my little friend."
      here-is-the-node-creation: |
        jenkins:
            nodes:
            - permanent:
                name: "static-agent1"
                remoteFS: "/home/jenkins"
                launcher:
                  jnlp:
                    workDirSettings:
                      disabled: true
                      failIfWorkDirIsMissing: false
                      internalDir: "remoting"
                      workDirPath: "/tmp"
            - permanent:
                name: "static-agent2"
                remoteFS: "/home/jenkins"
                launcher:
                  jnlp:
                    workDirSettings:
                      disabled: true
                      failIfWorkDirIsMissing: false
                      internalDir: "remoting"
                      workDirPath: "/tmp"
      here-is-the-user-security: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "${JENKINS_ADMIN_ID}"
                  name: "Admin de secret/jenkins"
                  password: "${JENKINS_ADMIN_PASSWORD}"
                  description: "testing user"
                - id: "pepe"
                  name: "usuario creado sin vault"
                  password: "pecas"
                  description: "testing user"
      here-is-the-job-creation: |
        jobs:
        - script: >
            pipelineJob('first-pipeline-seed') {
              description('testing')
              definition {
                cpsScm {
                  scm {
                    git {
                      branch('main')
                      remote {
                        url('https://github.com/alan-mas/jcasc-helm-example.git')
                      }
                    }
                  }
                  scriptPath('jobs/Jenkinsfile')
                }
              }
            }
              